PL/Controllers/SucursalController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    [Authorize(Roles = "Admin")]

    public class SucursalController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetAll()
        {
            ML.Sucursal sucursales = new ML.Sucursal();
            ML.Result resultSucursal = BL.Sucursal.GetAll();
            if (resultSucursal.Correct)
            {
                sucursales.Sucursales = resultSucursal.Objects.ToList();
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al traer los registros de las sucursales" + resultSucursal.ErrorMessage;
            }

            return View(sucursales);
        }
        [HttpGet] //Mostrar formulario
        public IActionResult Form(int? IdSucursal)
        {
            ML.Sucursal sucursal = new ML.Sucursal();

            if (IdSucursal == null)
            {
                return View(sucursal);
            }
            else
            {
                ML.Result result = BL.Sucursal.GetById(IdSucursal.Value);

                sucursal.IdSucursal = ((ML.Sucursal)result.Object).IdSucursal;
                sucursal.Nombre = ((ML.Sucursal)result.Object).Nombre;
                sucursal.Calle = ((ML.Sucursal)result.Object).Calle;
                sucursal.NumeroInterior = ((ML.Sucursal)result.Object).NumeroInterior;
                sucursal.NumeroExterior = ((ML.Sucursal)result.Object).NumeroExterior;
                sucursal.CP = ((ML.Sucursal)result.Object).CP;
                sucursal.Colonia = ((ML.Sucursal)result.Object).Colonia;
                sucursal.Municipio = ((ML.Sucursal)result.Object).Municipio;
                sucursal.Estado = ((ML.Sucursal)result.Object).Estado;
                sucursal.PaginaWeb = ((ML.Sucursal)result.Object).PaginaWeb;
                
                return View(sucursal);

            }
        }
        [HttpPost] //Recibe datos del formulario
        public ActionResult Form(ML.Sucursal sucursal)
        {
            if (ModelState.IsValid)
            {
                if (sucursal.IdSucursal == 0)//add
                {
                    ML.Result result = BL.Sucursal.Add(sucursal);//Trae la informacion directa desde el BL

                    if (result.Correct)
                    {
                        //mediante el ViewBag enviamos datos del controlador a la vista
                        ViewBag.Mensaje = "Se ha registrado correctamente la sucursal";
                    }
                    else
                    {
                        ViewBag.Mensaje = "No se ha registado correctamente la sucursal " + result.ErrorMessage;
                    }
                }
                else //update
                {

                    ML.Result result = BL.Sucursal.Update(sucursal);//Trae la informacion directa desde el BL

                    if (result.Correct)
                    {
                        //mediante el ViewBag enviamos datos del controlador a la vista
                        ViewBag.Mensaje = "Se ha actualizado correctamente la sucursal";
                    }
                    else
                    {
                        ViewBag.Mensaje = "No se ha podido actualizar conrrectamente la sucursal " + result.ErrorMessage;
                    }
                }
                return PartialView("Modal");
            }
            return View(sucursal);
        }

        public ActionResult Delete(int IdSucursal)
        {
            ML.Result result = BL.Sucursal.Delete(IdSucursal);//Trae la informacion directa desde el BL

            if (result.Correct)
            {
                ViewBag.Mensaje = "Se ha eliminado correctamente la sucursal";
            }
            else
            {
                ViewBag.Mensaje = "No se ha podido eliminar la sucursal. Error: " + result.ErrorMessage;
            }

            return PartialView("Modal");
        }
    }
}

PL/Views/Sucursal/Form.cshtml
@model ML.Sucursal
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2>Sucursal</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <h5> Ingrese los datos de la sucursal</h5>
        </div>
        <hr />
    </div>

    <form asp-action="Form" asp-controller="Sucursal" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-4">
                <label asp-for="IdSucursal" hidden></label>
                <input asp-for="IdSucursal" hidden class="form-control" />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4">
                <label asp-for="Nombre"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger" id="lblCurpErrorMessage"></span>
            </div>

             <div class="col-md-4">
            <label asp-for="Calle"></label>
            <input asp-for="Calle" class="form-control" />
            <span asp-validation-for="Calle" class="text-danger" id="lblCurpErrorMessage"></span>
            </div>

            <div class="col-md-4">
            <label asp-for="NumeroInterior"></label>
                <input asp-for="NumeroInterior" class="form-control" />
                <span asp-validation-for="NumeroInterior" class="text-danger" id="lblCurpErrorMessage"></span>
            </div>
        </div>
        <br>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="NumeroExterior"></label>
                <input asp-for="NumeroExterior" class="form-control" />
                <span asp-validation-for="NumeroExterior" class="text-danger" id="lblCurpErrorMessage"></span>
            </div>

            <div class="col-md-4">
                <label asp-for="CP"></label>
                <input asp-for="CP" class="form-control" />
                <span asp-validation-for="CP" class="text-danger" id="lblCurpErrorMessage"></span>
            </div>

            <div class="col-md-4">
                <label asp-for="Colonia"></label>
                <input asp-for="Colonia" class="form-control" />
                <span asp-validation-for="Colonia" class="text-danger" id="lblCurpErrorMessage"></span>
            </div>
        </div>
        <br>

        <div class="row">
            <div class="col-md-4">
                <label asp-for="Municipio"></label>
                <input asp-for="Municipio" class="form-control" />
                <span asp-validation-for="Municipio" class="text-danger" id="lblCurpErrorMessage"></span>
            </div>

            <div class="col-md-4">
                <label asp-for="Estado"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger" id="lblCurpErrorMessage"></span>
            </div>

            <div class="col-md-4">
                <label asp-for="PaginaWeb"></label>
                <input asp-for="PaginaWeb" class="form-control" />
                <span asp-validation-for="PaginaWeb" class="text-danger" id="lblCurpErrorMessage"></span>
            </div>
        </div>
        <br>

        <div class="row">
            <div class="col-md-1 offset-md-5">
                <input type="submit" class="btn btn-success" value="Guardar" />
            </div>
            <div class="col-md-1">
                <a asp-action="GetAll" asp-controller="Sucursal" class="btn btn-danger">Cancelar</a>
            </div>
        </div>
    </form>
</div>

PL/Views/Sucursal/GetAll.cshtml
@model ML.Sucursal
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class=row>
        <div class="text-center pb-4">
            <h2>Sucursales</h2>

        </div>
        @* <div class="col-md-6 col-sm-12">
            <h2>Detalle</h2>

        </div> *@
    </div>

    <div class="row">
        <div class="col-md-12">
            <h5>Seleccione una sucursal para editarlo o + para agregar...</h5>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col">

            <div style="float:inline-end;" class="mb-3">
                @Html.ActionLink("+", "Form", "Sucursal", htmlAttributes: new { @class = "btn btn-success " })
            </div>
        </div>
    </div>

    @if (Model.Sucursales != null)
    {
        @if (Model.Sucursales.Count > 0)

        {
            <div class="row">
                <table class="table table-hover table-striped table-bordered table-responsive" id="table_sucursales">
                    <thead>
                        <tr class="table-secondary">
                            <td>Editar</td>
                            <td style="display :none;">id</td>
                            <td>Nombre</td>
                            <td>Direccion</td>
                            <td>Pagina Web</td>
                            <td>Eliminar</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ML.Sucursal sucursal in Model.Sucursales)
                        {
                            <tr>
                                <td style="text-align: center; vertical-align: middle;"><a class="btn btn-outline-warning glyphicon" href="@Url.Action("Form", "Sucursal", new { IdSucursal = sucursal.IdSucursal })"><img src="/Images/editar.png"></a></td>
                                <td style="display :none;">@sucursal.IdSucursal </td>
                                <td>@sucursal.Nombre </td>
                                <td>@sucursal.Calle @sucursal.NumeroInterior @sucursal.NumeroExterior, @sucursal.Colonia @sucursal.Municipio @sucursal.CP, @sucursal.Estado </td>
                                <td>@sucursal.PaginaWeb</td>
                                <td style="text-align: center; vertical-align: middle;"><a class="btn btn-outline-danger glyphicon-trash" href="@Url.Action("Delete", "Sucursal", new { IdSucursal = sucursal.IdSucursal})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"><img src="/Images/remove.png"></a></td>

                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
        else
        {
            <div class="alert alert-danger" role="alert">No hay sucursales registradas. Da click en + para agregar una nueva sucursal.</div>
        }
    }
   

</div>

PL/Views/Sucursal/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


<div class="modal fade" id="modalValidacion" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Aviso</h4>
            </div>
            <div class="modal-body">
                <p>@ViewBag.Mensaje</p>
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>*@
                @Html.ActionLink("Regresar", "GetAll", "Sucursal", new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal('show');
</script>