PL/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ML;
using PL.Data;
using System.ComponentModel.DataAnnotations;


namespace PL.Controllers
{
    [Authorize(Roles ="Admin")]

    public class ProductoController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ProductoController(ApplicationDbContext context) 
        {
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetAll()
        {
            ML.Producto productos = new ML.Producto();

            ML.Result resultProducto = BL.Producto.GetAll();

            if (resultProducto.Correct)
            {
                productos.Productos = resultProducto.Objects.ToList();
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al traer los registros de los productos" + resultProducto.ErrorMessage;
            }

            return View(productos);
        }

        [HttpGet] //Mostrar formulario
        public IActionResult Form(int? IdProducto)
        {
            ML.Producto producto = new ML.Producto();

            //drop down list marca
            ML.Result resultMarca = BL.Marca.GetAll();
            producto.Marca = new ML.Marca();
            producto.Marca.Marcas = resultMarca.Objects;
            
            //drop down list proveedor
            ML.Result resultProveedor = BL.Proveedor.GetAll();
            producto.Proveedor = new ML.Proveedor();
            producto.Proveedor.Proveedores = resultProveedor.Objects;

            //drop down list departamento
            ML.Result resultDepartamento = BL.Departamento.GetAll();
            producto.Departamento = new ML.Departamento();
            //producto.Departamento.Departamentos = resultDepartamento.Objects;//temporalDepartamento

            ////drop down list area
            ML.Result resultArea = BL.Area.GetAll();
            producto.Departamento.Area = new ML.Area();
            producto.Departamento.Area.Areas = resultArea.Objects;



            if (IdProducto == null)
            {
                return View(producto);
            }
            else
            {
                ML.Result result = BL.Producto.GetById(IdProducto.Value);

                producto.IdProducto = ((ML.Producto)result.Object).IdProducto;
                producto.Nombre = ((ML.Producto)result.Object).Nombre;
                producto.Descripcion = ((ML.Producto)result.Object).Descripcion;
                producto.FechaIngreso = ((ML.Producto)result.Object).FechaIngreso;
                producto.PrecioUnitario = ((ML.Producto)result.Object).PrecioUnitario;
                producto.CodigoBarras = ((ML.Producto)result.Object).CodigoBarras;
                producto.Imagen = ((ML.Producto)result.Object).Imagen;
                producto.Modelo = ((ML.Producto)result.Object).Modelo;

                //ddl se inicalizan arriba
                producto.Marca.IdMarca = ((ML.Producto)result.Object).Marca.IdMarca;
                producto.Proveedor.IdProveedor = ((ML.Producto)result.Object).Proveedor.IdProveedor;
                producto.Departamento.IdDepartamento = ((ML.Producto)result.Object).Departamento.IdDepartamento;

                //Trae el departamento correcto
                producto.Departamento.Departamentos = resultDepartamento.Objects;//temporalDepartamento

                //se inicializa arriba area
                int? IdArea = producto.Departamento.Area.IdArea = ((ML.Producto)result.Object).Departamento.Area.IdArea;//temporalArea
                producto.Departamento.Area.Areas = resultArea.Objects;
                ML.Result resultIdArea = BL.Departamento.GetByIdArea(IdArea);
                producto.Departamento.Departamentos = resultIdArea.Objects;

                return View(producto);

            }
        }

        [HttpPost] //Recibe datos del formulario
        public ActionResult Form(ML.Producto producto, IFormFile? imgProducto)
        //public ActionResult Form(ML.Producto producto)
        {

            if (imgProducto != null)//Aplica para ambos add y update
            {
                producto.Imagen = ConvertToBytes(imgProducto);//Se convierte la imagen a bytes

            }
            if (ModelState.IsValid)
            {
                if (producto.IdProducto == 0)//add
                {
                    ML.Result result = BL.Producto.Add(producto);//Trae la informacion directa desde el BL

                    if (result.Correct)
                    {
                        //mediante el ViewBag enviamos datos del controlador a la vista
                        ViewBag.Mensaje = "Se ha registrado correctamente el producto";
                    }
                    else
                    {
                        ViewBag.Mensaje = "No se ha registado conrrectamente el producto " + result.ErrorMessage;
                    }
                }
                else //update
                {

                    ML.Result result = BL.Producto.Update(producto);//Trae la informacion directa desde el BL

                    if (result.Correct)
                    {
                        //mediante el ViewBag enviamos datos del controlador a la vista
                        ViewBag.Mensaje = "Se ha actualizado correctamente el producto";
                    }
                    else
                    {
                        ViewBag.Mensaje = "No se ha podido actualizar conrrectamente el producto " + result.ErrorMessage;
                    }
                }
                return PartialView("Modal");
            }

            //drop down list proveedor
            ML.Result resultMarca = BL.Marca.GetAll();
            producto.Marca = new ML.Marca();
            producto.Marca.Marcas = resultMarca.Objects;
            //drop down list proveedor
            ML.Result resultProveedor = BL.Proveedor.GetAll();
            producto.Proveedor = new ML.Proveedor();
            producto.Proveedor.Proveedores = resultProveedor.Objects;
            
            ML.Result resultDepartamentor = BL.Departamento.GetAll();
            producto.Departamento = new ML.Departamento();
            producto.Departamento.Departamentos = resultDepartamentor.Objects;

            ////drop down list departamento
            producto.Departamento = new ML.Departamento();

            //drop down list area
            ML.Result resultArea = BL.Area.GetAll();
            producto.Departamento.Area = new ML.Area();
            producto.Departamento.Area.Areas = resultArea.Objects;

            return View(producto);
        }

        public ActionResult Delete(int IdProducto)
        {
            ML.Result result = BL.Producto.Delete(IdProducto);//Trae la informacion directa desde el BL

            if (result.Correct)
            {
                ViewBag.Mensaje = "Se ha eliminado correctamente el producto";
            }
            else
            {
                ViewBag.Mensaje = "No se ha podido eliminar el producto. Error: " + result.ErrorMessage;
            }

            return PartialView("Modal");
        }

        /**Convertir img a bytes**/
        public byte[] ConvertToBytes(IFormFile image)
        {
        
            using var fileStream = image.OpenReadStream();

            byte[] imageBytes = new byte[fileStream.Length];
            fileStream.Read(imageBytes, 0, (int)fileStream.Length);

            return imageBytes;
        }
        //DDL
        public JsonResult GetDepartamentosList(int IdArea)
        {
            //BL- > Departamentos de determinada Area 
            ML.Result resultDepartamentos = BL.Departamento.GetByIdArea(IdArea);
            //crear un nuevo stored GrupoGetByIdPlantel -> DepartamentoGetByIdArea
            return Json(resultDepartamentos.Objects);
        }
    }
}

PL/Controllers/SucursalProductoController.cs
using Microsoft.AspNetCore.Mvc;
using ML;
using PL.Data;
using System.Net.Mail;
using System.Net;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Authorization;

namespace PL.Controllers
{
    [Authorize(Roles = "Admin")]

    public class SucursalProductoController : Controller
    {
        private readonly IConfiguration _configuration;
        public SucursalProductoController(IConfiguration configuration)
        {
            _configuration = configuration;
        }


        public IActionResult Index()
        {
            //ML.Sucursal sucursal = new ML.Sucursal();
            //ML.Result resultSucursal = BL.Sucursal.GetAll();
            //sucursal.Sucursales = resultSucursal.Objects;
            //return View(sucursal);
            ML.SucursalProducto sucursalP = new ML.SucursalProducto();
            sucursalP.Sucursal = new ML.Sucursal();

            ML.Result resultSucursal = BL.Sucursal.GetAll();
            sucursalP.Sucursal.Sucursales = resultSucursal.Objects;
            return View(sucursalP);
        }

        public IActionResult GetSucursal(int IdSucursal)
        {
            ML.SucursalProducto sucursalp = new ML.SucursalProducto();
            ML.Result resultSucursal = BL.SucursalProducto.GetbySucursal(IdSucursal);

            sucursalp.SucuralesProductos = resultSucursal.Objects;

            return PartialView("ResulltadoSucursalP", sucursalp);
        }
        public IActionResult UpdateStock(int idStock, int txtStock)
        {
            ML.Result resultStock = BL.SucursalProducto.UpdateStock(idStock, txtStock);
            if (resultStock.Correct)
            {
                //ViewBag.Mensaje = "Se ha actualizado correctamente el stock";
                return Json(new { success = true, message = "Se ha actualizado correctamente el stock", nuevoValor = resultStock.Object });
            }
            else
            {
                //ViewBag.Mensaje = "No se ha podido actualizado el stock. Error: " + resultStock.ErrorMessage;
                return Json(new { success = false, message = "No se ha podido actualizar correctamente el stock" });

            }

            //return PartialView("Modal");
        }
        public ActionResult Delete(int IdSucursalProducto)
        {
            ML.Result result = BL.SucursalProducto.Delete(IdSucursalProducto);//Trae la informacion directa desde el BL

            if (result.Correct)
            {
                ViewBag.Mensaje = "Se ha eliminado correctamente el producto de la sucursal";
                ViewBag.SucProduct = IdSucursalProducto;

            }
            else
            {
                ViewBag.Mensaje = "No se ha podido eliminar el producto  de la sucursal. Error: " + result.ErrorMessage;
            }

            return PartialView("Modal");
        }
    }
}

PL/Views/SucursalProducto/Index.cshtml
@model ML.SucursalProducto
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("GetSucursal", "SucursalProducto", FormMethod.Post, new { enctype = "multipart/form-data" })) //se hace uso del form Post
{
    <div id="formulario" >

        <div class="row">
            <div class="col-md-4">
                @Html.LabelFor(producto => Model.Sucursal.Sucursales)
                @Html.DropDownListFor(producto => Model.Sucursal.IdSucursal, new SelectList(Model.Sucursal.Sucursales, "IdSucursal", "Nombre"), "Selecciona una Sucursal", new { @id = "ddlSucursal", @class = "form-control" })
                @Html.ValidationMessageFor(model => Model.Sucursal.IdSucursal, "", new { @class = "text-danger", @id = "lblSucursalErrorMessage" })
            </div>
        </div>
        <br>

        <div class="row">
            <div class="col-md-2 ">
                <input type="submit" class="btn btn-primary" value="Mostrar sucursal" onclick="return mostrarSucursal();" />
            </div>
        </div>
    </div>
}

<div id="sucursalesProductos">

</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript">
    function mostrarSucursal(){
        var selectedSucursal = $('#ddlSucursal').val();
        console.log("selectedSucursal: " + selectedSucursal);
        $.ajax({
            type: 'POST',
            url: '@Url.Action("GetSucursal", "SucursalProducto")',
            data:{IdSucursal:selectedSucursal},
            success: function (data) {
                $('#sucursalesProductos').html(data);
            },
            error: function(){
                alert('error a traer los datos');

            }
        });
        return false;
    }
</script>

PL/Views/SucursalProducto/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


<div class="modal fade" id="modalValidacion" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Aviso</h4>
            </div>
            <div class="modal-body">
                <p>@ViewBag.Mensaje</p>
            </div>
            <div class="modal-footer">
                @*<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>*@
                @* <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button> *@
                @Html.ActionLink("Regresar", "Index", "SucursalProducto", new { @class = "btn btn-primary"  })

            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal('show');
        setTimeout(function () {
            $('#StockModal').modal('hide');
        }, 3000); 
</script>

PL/Views/SucursalProducto/ResulltadoSucursalP.cshtml
@model ML.SucursalProducto
<!-- Incluye Bootstrap JS y CSS -->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
@if (Model.SucuralesProductos != null)
{
    <div class="row m-5">
        <table class="table table-hover table-striped table-bordered table-responsive" id="table_sucursales">
            <thead>
                <tr class="table-secondary">
                    <td>Editar</td>
                    <td style="display :none;">id</td>
                    <td>Sucursal</td>
                    <td>Producto</td>
                    <td>Stock</td>
                    <td>Imagen</td>
                    <td>Eliminar</td>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.SucursalProducto producto in Model.SucuralesProductos)
                {
                    <tr>
                        @*<td style="text-align: center; vertical-align: middle;"><a class="btn btn-warning glyphicon" href="@Url.Action("Form", "Producto", new { IdProducto = producto.Producto.IdProducto })"><i class="bi bi-pencil-square" style="color: ivory"></i></a></td>*@
                        <td style="text-align: center; vertical-align: middle;">
                            <a class="btn btn-outline-warning btn-EditarStock" href="#" id="EditarStock" data-idsucursalproducto="@producto.IdSucursalProducto"><img src="/Images/editar.png"></a>
                        </td>
                        <td style="display :none;">@producto.Producto.IdProducto </td>
                        <td>@producto.Sucursal.Nombre</td>
                        <td>@producto.Producto.Nombre </td>
                        <td id="stockValor-@producto.IdSucursalProducto">@producto.Stock </td>
                        <td>
                            @if (producto.Producto.Imagen != null)
                            {
                                <img src="data:image/jpg;base64,@Convert.ToBase64String(producto.Producto.Imagen)" style="width:100px; height:100px" />
                            }
                            else
                            {
                                <img id="imgUsuario" src="~/Images/producto.png" style="width:150px; height:150px" />
                            }
                        </td>

                        <td style="text-align: center; vertical-align: middle;"><a class="btn btn-outline-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "SucursalProducto", new { IdSucursalProducto = producto.IdSucursalProducto})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"><img src="/Images/remove.png">   </a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div class="row m-5">
        <div class="col">
            <div class="alert alert-danger" role="alert">No existen registros.</div>

        </div>
    </div>

}

<!-- Modal -->
<div class="modal fade" id="StockModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modificar stock</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <label>Ingrese el stock</label>
                <input type="text" id="txtStock" class="form-control" placeholder="Stock" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="guardarStock">Guardar</button>
            </div>
        </div>
    </div>
</div>

<!-- Incluye jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>

<script>
    $(document).ready(function () {

        $('.btn-EditarStock').click(function (e) {
            e.preventDefault();
                // para evitar la acumulación de click
            $('#guardarStock').off('click');
            var idSucursalProduct = $(this).data('idsucursalproducto');
         
            $('#StockModal').modal('show');  /*abrir*/
            $('#guardarStock').click(function () {
                var txtStock = $('#txtStock').val();
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("UpdateStock","SucursalProducto")',
                    data: { idStock: idSucursalProduct, txtStock: txtStock },
                    success: function (result) {
                        if (result.success) {

                            $('#StockModal').modal('hide');
                            alert('Stock actualizado Correctamente: '+ result.message);
                            // var ns = result.nuevoValor;
                            /*Pendiente */
                            $('#stockValor-' + idSucursalProduct).text(result.nuevoValor);
                            $('#txtStock').val('');
                        }
                        else {
                            alert('se  ha producido un error: ' + result.message);
                        }
                    },
                    error: function (result) {
                        alert('Error en la consulta.' + result.ErrorMessage);
                    }
                });
            });
        })
    });

</script>