PL/Controllers/HistorialController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    [Authorize(Roles = "User")]


    public class HistorialController : Controller
    {

        private UserManager<IdentityUser> userManager;// sin esta estancia no se puede hacer un crud y apunta a la tabla rol (RolManager)
        private readonly SignInManager<IdentityUser> _signInManager;

        public HistorialController(UserManager<IdentityUser> userMgr, SignInManager<IdentityUser> signInManager) //contructor de la clase la inicializa, si no se inicializa no se tiene acceso a la base de datos
        {
            userManager = userMgr;
            _signInManager = signInManager;

        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetAll()
        {
            string userId = userManager.GetUserId(User);

            ML.Venta ventas = new ML.Venta();
            ML.Result resultHistorial = BL.Historial.GetAll(userId);
            if (resultHistorial.Correct)
            {
                ventas.Ventas = resultHistorial.Objects.ToList();
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al traer los registros";
            }

            return View(ventas);
        }

        public async Task<IActionResult> GetProductoHistorial(int IdVenta)
        {
            string userId = userManager.GetUserId(User);

            ML.VentaProducto ventaProducto = new ML.VentaProducto();
            ML.Result resultHistorial = BL.Historial.GetProductoHistorial(IdVenta, userId);
          
            if (resultHistorial.Correct)
            {
                ventaProducto.VentasProductos = resultHistorial.Objects.ToList();
            }
            else
            {
                ViewBag.Message = "Para poder ver este detalle de compra, ingrese con su cuenta correcta por favor";
                await _signInManager.SignOutAsync();
                return RedirectToAction("Index","Home");

            }

            return View(ventaProducto);
        }
    }
}

PL/Views/Historial/GetAll.cshtml
@model ML.Venta;
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model.Ventas.Count > 0)
{
    <section class="h-100" style="background-color: #eee;">
        <div class="container h-100 py-5">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-10">

                    <div class="d-flex justify-content-between align-items-center mb-4">
                        <h3 class="fw-normal mb-0 text-black">Historial de compras</h3>
                       
                    </div>
                    @foreach (ML.Venta venta in Model.Ventas)
                    {
                        <div class="card rounded-3 mb-4">
                            <div class="card-body p-4">
                                <div class="row d-flex justify-content-between align-items-center">
                                    <div class="col-md-2 col-lg-2 col-xl-3">
                                        <img src="~/Images/producto-default1.jpg"
                                             class="img-fluid rounded-3" alt="Cotton T-shirt">
                                             @* <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-shopping-carts/img1.webp"
                                             class="img-fluid rounded-3" alt="Cotton T-shirt"> *@
                                    </div>
                                    <div class="col-md-3 col-lg-3 col-xl-3">
                                        <p class="lead fw-normal mb-2">Numero de venta: @venta.IdVenta</p>
                                        <p><span class="text-muted">Total: </span>$@venta.Total</p> 
                                        <p><span class="text-muted">Fecha: </span>@venta.Fecha</p>
                                    </div>
                                  
                                   @*  <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                        <h5 class="mb-0">Pagado</h5>
                                        <h5 class="mb-0">$@venta.Total</h5>
                                    </div> *@
                                    <div class="col-md-3 col-lg-3 col-xl-2 d-flex">

                                        @* <button type="button" class="btn btn-outline-primary">Ver Detalles</button> *@
                                        <a class="btn btn-outline-primary" href="@Url.Action("GetProductoHistorial", "Historial", new { IdVenta = venta.IdVenta})">Ver detalles</a>

                                    </div>
                                   
                                </div>
                            </div>
                        </div>

                    }
                </div>
            </div>
        </div>
    </section>
}
else
{
    <div class="alert alert-danger" role="alert">No hay un historial de compra.</div>

}

PL/Views/Historial/GetProductoHistorial.cshtml
@model ML.VentaProducto
@{
    ViewData["Title"] = "GetProductoHistorial";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Model.VentasProductos != null)
{
    @if (Model.VentasProductos.Count > 0)
    {
        <section class="h-100" style="background-color: #eee;">
            <div class="container h-100 py-5">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-10">

                        <div class="d-flex justify-content-between align-items-center mb-4">
                            <h3 class="fw-normal mb-0 text-black">Detalle de compra</h3>

                        </div>
                        @* START CARD *@
                        @foreach (ML.VentaProducto ventaProducto in Model.VentasProductos)
                        {
                            <div class="card rounded-3 mb-4">
                                <div class="card-body p-4">
                                    <div class="row d-flex justify-content-between align-items-center">
                                        <div class="col-md-2 col-lg-2 col-xl-2">

                                            @if (ventaProducto.SucursalProducto.Producto.Imagen != null)
                                            {
                                                <img src="data:image/jpg;base64,@Convert.ToBase64String(ventaProducto.SucursalProducto.Producto.Imagen)" class="img-fluid rounded-3" />
                                            }
                                            else
                                            {
                                                <img id="imgUsuario" src="~/Images/producto.png" style="width:150px; height:150px" />
                                            }
                                        </div>
                                        <div class="col-md-3 col-lg-3 col-xl-3">
                                            <p class="lead fw-normal mb-2">@ventaProducto.SucursalProducto.Producto.Nombre</p>
                                            <p><span class="text-muted">Cantidad: </span>@ventaProducto.Cantidad</p>
                                            <p><span class="text-muted">Precio Unitario: </span>@ventaProducto.SucursalProducto.Producto.PrecioUnitario</p>
                                            <p><span class="text-muted">Descripcion: </span>@ventaProducto.SucursalProducto.Producto.Descripcion</p>
                                        </div>
                                        <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                                            <h5 class="mb-0">Subtotal</h5>
                                            <h6 class="mb-0">@ventaProducto.SubTotal?.ToString("C")</h6>
                                        </div>
                                        <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                            <a href="#!" class="text-danger"><i class="fas fa-trash fa-lg"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        }
                        @* END CARD *@

                        @*  <div class="card mb-4">
                <div class="card-body p-4 d-flex flex-row">
                <div class="form-outline flex-fill">
                <input type="text" id="form1" class="form-control form-control-lg" />
                <label class="form-label" for="form1">Discound code</label>
                </div>
                <button type="button" class="btn btn-outline-warning btn-lg ms-3">Apply</button>
                </div>
                </div>

                <div class="card">
                <div class="card-body">
                <button type="button" class="btn btn-warning btn-block btn-lg">Proceed to Pay</button>
                </div>
                </div> *@


                    </div>
                </div>
            </div>
        </section>
    }
    else
    {
        <div class="alert alert-danger" role="alert">No hay un historial de compra.</div>
    }
}
else
{
    <div class="alert alert-danger" role="alert">@ViewBag.Message</div>

}