PL/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ML;
using PL.Data;
using System.ComponentModel.DataAnnotations;


namespace PL.Controllers
{
    [Authorize(Roles ="Admin")]

    public class ProductoController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ProductoController(ApplicationDbContext context) 
        {
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetAll()
        {
            ML.Producto productos = new ML.Producto();

            ML.Result resultProducto = BL.Producto.GetAll();

            if (resultProducto.Correct)
            {
                productos.Productos = resultProducto.Objects.ToList();
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al traer los registros de los productos" + resultProducto.ErrorMessage;
            }

            return View(productos);
        }

        [HttpGet] //Mostrar formulario
        public IActionResult Form(int? IdProducto)
        {
            ML.Producto producto = new ML.Producto();

            //drop down list marca
            ML.Result resultMarca = BL.Marca.GetAll();
            producto.Marca = new ML.Marca();
            producto.Marca.Marcas = resultMarca.Objects;
            
            //drop down list proveedor
            ML.Result resultProveedor = BL.Proveedor.GetAll();
            producto.Proveedor = new ML.Proveedor();
            producto.Proveedor.Proveedores = resultProveedor.Objects;

            //drop down list departamento
            ML.Result resultDepartamento = BL.Departamento.GetAll();
            producto.Departamento = new ML.Departamento();
            //producto.Departamento.Departamentos = resultDepartamento.Objects;//temporalDepartamento

            ////drop down list area
            ML.Result resultArea = BL.Area.GetAll();
            producto.Departamento.Area = new ML.Area();
            producto.Departamento.Area.Areas = resultArea.Objects;



            if (IdProducto == null)
            {
                return View(producto);
            }
            else
            {
                ML.Result result = BL.Producto.GetById(IdProducto.Value);

                producto.IdProducto = ((ML.Producto)result.Object).IdProducto;
                producto.Nombre = ((ML.Producto)result.Object).Nombre;
                producto.Descripcion = ((ML.Producto)result.Object).Descripcion;
                producto.FechaIngreso = ((ML.Producto)result.Object).FechaIngreso;
                producto.PrecioUnitario = ((ML.Producto)result.Object).PrecioUnitario;
                producto.CodigoBarras = ((ML.Producto)result.Object).CodigoBarras;
                producto.Imagen = ((ML.Producto)result.Object).Imagen;
                producto.Modelo = ((ML.Producto)result.Object).Modelo;

                //ddl se inicalizan arriba
                producto.Marca.IdMarca = ((ML.Producto)result.Object).Marca.IdMarca;
                producto.Proveedor.IdProveedor = ((ML.Producto)result.Object).Proveedor.IdProveedor;
                producto.Departamento.IdDepartamento = ((ML.Producto)result.Object).Departamento.IdDepartamento;

                //Trae el departamento correcto
                producto.Departamento.Departamentos = resultDepartamento.Objects;//temporalDepartamento

                //se inicializa arriba area
                int? IdArea = producto.Departamento.Area.IdArea = ((ML.Producto)result.Object).Departamento.Area.IdArea;//temporalArea
                producto.Departamento.Area.Areas = resultArea.Objects;
                ML.Result resultIdArea = BL.Departamento.GetByIdArea(IdArea);
                producto.Departamento.Departamentos = resultIdArea.Objects;

                return View(producto);

            }
        }

        [HttpPost] //Recibe datos del formulario
        public ActionResult Form(ML.Producto producto, IFormFile? imgProducto)
        //public ActionResult Form(ML.Producto producto)
        {

            if (imgProducto != null)//Aplica para ambos add y update
            {
                producto.Imagen = ConvertToBytes(imgProducto);//Se convierte la imagen a bytes

            }
            if (ModelState.IsValid)
            {
                if (producto.IdProducto == 0)//add
                {
                    ML.Result result = BL.Producto.Add(producto);//Trae la informacion directa desde el BL

                    if (result.Correct)
                    {
                        //mediante el ViewBag enviamos datos del controlador a la vista
                        ViewBag.Mensaje = "Se ha registrado correctamente el producto";
                    }
                    else
                    {
                        ViewBag.Mensaje = "No se ha registado conrrectamente el producto " + result.ErrorMessage;
                    }
                }
                else //update
                {

                    ML.Result result = BL.Producto.Update(producto);//Trae la informacion directa desde el BL

                    if (result.Correct)
                    {
                        //mediante el ViewBag enviamos datos del controlador a la vista
                        ViewBag.Mensaje = "Se ha actualizado correctamente el producto";
                    }
                    else
                    {
                        ViewBag.Mensaje = "No se ha podido actualizar conrrectamente el producto " + result.ErrorMessage;
                    }
                }
                return PartialView("Modal");
            }

            //drop down list proveedor
            ML.Result resultMarca = BL.Marca.GetAll();
            producto.Marca = new ML.Marca();
            producto.Marca.Marcas = resultMarca.Objects;
            //drop down list proveedor
            ML.Result resultProveedor = BL.Proveedor.GetAll();
            producto.Proveedor = new ML.Proveedor();
            producto.Proveedor.Proveedores = resultProveedor.Objects;
            
            ML.Result resultDepartamentor = BL.Departamento.GetAll();
            producto.Departamento = new ML.Departamento();
            producto.Departamento.Departamentos = resultDepartamentor.Objects;

            ////drop down list departamento
            producto.Departamento = new ML.Departamento();

            //drop down list area
            ML.Result resultArea = BL.Area.GetAll();
            producto.Departamento.Area = new ML.Area();
            producto.Departamento.Area.Areas = resultArea.Objects;

            return View(producto);
        }

        public ActionResult Delete(int IdProducto)
        {
            ML.Result result = BL.Producto.Delete(IdProducto);//Trae la informacion directa desde el BL

            if (result.Correct)
            {
                ViewBag.Mensaje = "Se ha eliminado correctamente el producto";
            }
            else
            {
                ViewBag.Mensaje = "No se ha podido eliminar el producto. Error: " + result.ErrorMessage;
            }

            return PartialView("Modal");
        }

        /**Convertir img a bytes**/
        public byte[] ConvertToBytes(IFormFile image)
        {
        
            using var fileStream = image.OpenReadStream();

            byte[] imageBytes = new byte[fileStream.Length];
            fileStream.Read(imageBytes, 0, (int)fileStream.Length);

            return imageBytes;
        }
        //DDL
        public JsonResult GetDepartamentosList(int IdArea)
        {
            //BL- > Departamentos de determinada Area 
            ML.Result resultDepartamentos = BL.Departamento.GetByIdArea(IdArea);
            //crear un nuevo stored GrupoGetByIdPlantel -> DepartamentoGetByIdArea
            return Json(resultDepartamentos.Objects);
        }
    }
}

PL/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Rewrite;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using ML;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace PL.Controllers
{
    [Authorize(Roles = "Admin")]

    public class RoleController : Controller
    {
        private RoleManager<IdentityRole> roleManager;// sin esta estancia no se puede hacer un crud y apunta a la tabla rol (RolManager)
        public RoleController(RoleManager<IdentityRole> roleMgr) //contructor de la clase la inicializa, si no se inicializa no se tiene acceso a la base de datos
        {
            roleManager = roleMgr;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            ML.Role rol = new ML.Role();
            rol.Roles = new List<object>();

            var Roles = roleManager.Roles.ToList();
            return View(Roles);
        }

        //[HttpPost]
        //public async Task<IActionResult> Form([Required] Microsoft.AspNetCore.Identity.IdentityRole rol)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        IdentityResult result = await roleManager.CreateAsync(new IdentityRole(rol.Name));
        //        if (result.Succeeded)
        //        {
        //            return RedirectToAction("GetAll");
        //        }
        //        else
        //        {

        //        }
        //        //  Errors(result);
        //    }
        //    return View(rol);
        //}

        [HttpPost]
        public async Task<IActionResult> Form([Required] Microsoft.AspNetCore.Identity.IdentityRole rol)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result;

                //IdentityRole role = await roleManager.FindByIdAsync(rol.Id.ToString());
                var rolExists = await roleManager.FindByIdAsync(rol.Id);
                //var rolExists = roleManager.Roles.FirstOrDefault(r => r.Id == rol.Id);


                if (rolExists == null)
                {
                    //Add
                    result = await roleManager.CreateAsync(new IdentityRole(rol.Name));
                    if (result.Succeeded)
                    {
                        return RedirectToAction("GetAll");
                    }
                    else
                    {
                    }
                }
                else
                {

                    //result = await roleManager.UpdateAsync(new IdentityRole(rol.Name));
                    //rolExists.Name = "Admin";
                    result = await roleManager.UpdateAsync(rolExists);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("GetAll");
                    }
                    else
                    {
                        
                    }
                }

                //if (rol.Id == "")//add
                //{
                //    result = await roleManager.CreateAsync(new IdentityRole(rol.Name));
                //    if (result.Succeeded)
                //    {
                //        return RedirectToAction("GetAll");
                //    }
                //    else
                //    {

                //    }
                //    //  Errors(result);
                //}
                //else//update
                //{
                //    result = await roleManager.UpdateAsync(rol);
                //    if (result.Succeeded)
                //    {
                //        return RedirectToAction("GetAll");
                //    }

                //}

            }
            return View(rol);
        }


        //public async Task<IActionResult> Form(Guid? IdRole)
        //{
        //    //IdentityRole rol = new IdentityRole();
        //    //role.Id = await roleManager.FindByIdAsync(IdRole.ToString());

        //    IdentityRole role = await roleManager.FindByIdAsync(IdRole.ToString());
        //    if (role == null)
        //    {
        //        return View(role);

        //    }
        //    else
        //    {
        //        var result = await roleManager.UpdateAsync(role);
        //        if (result.Succeeded)
        //        {
        //            return RedirectToAction("GetAll");
        //        }
        //        {
        //            foreach (var error in result.Errors)
        //            {
        //                ModelState.AddModelError("No se pudo actualizar el rol", error.Description);
        //            }
        //        }
        //        return View(role);

        //    }
        //}

        //public IActionResult Form(Guid? IdRole)
        public async Task<IActionResult> Form(Guid? IdRole)
        {
            //IdentityRole rol = new IdentityRole();

            //IdentityRole role = roleManager.FindByIdAsync(IdRole.ToString()).Result;
            //IdentityRole role = await roleManager.FindByIdAsync(IdRole.ToString());
            //IdentityRole role = roleManager.FindByIdAsync(IdRole.ToString()).Result;

            if (IdRole == null) 
            {
                return View(new IdentityRole());
            }
            else
            {
                //IdentityRole roles = roleManager.Roles.FirstOrDefault(r => r.Id == IdRole.ToString());
                //var roles = roleManager.Roles.FirstOrDefault(r => r.Id == IdRole.ToString());

                var roles = await roleManager.FindByIdAsync(IdRole.ToString());
                return View(roles);

            }

        }


        public async Task<IActionResult> Delete(Guid? IdRole)
        {
            //IdentityRole rol = new IdentityRole();
             var role = await roleManager.FindByIdAsync(IdRole.ToString());
            if (role != null)
            {
                var result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("GetAll");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("No se pude eliminar el rol", error.Description);
                    }
                }
            }
            else
            {
                 
            }

            return View(role);
        }
    }
}

PL/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace PL.Controllers
{
    [Authorize]

    public class UsuarioController : Controller
    {
        private UserManager<IdentityUser> userManager;// sin esta estancia no se puede hacer un crud y apunta a la tabla rol (RolManager)
        public UsuarioController(UserManager<IdentityUser> userMgr) //contructor de la clase la inicializa, si no se inicializa no se tiene acceso a la base de datos
        {
            userManager = userMgr;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            ML.Usuario user = new ML.Usuario();
            user.Usuarios = new List<object>();

            var Usuarios = userManager.Users.ToList();
            return View(Usuarios);
        }

        [HttpPost]
        public async Task<IActionResult> Form([Required] Microsoft.AspNetCore.Identity.IdentityUser user)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result;
     
                var userExists = await userManager.FindByIdAsync(user.Id);

                if (userExists == null)
                {
                    //Add
                    //result = await userManager.CreateAsync(new IdentityUser(user.UserName));
                    result = await userManager.CreateAsync(new IdentityUser(user.PhoneNumber));
                    if (result.Succeeded)
                    {
                        return RedirectToAction("GetAll");
                    }
                    else
                    {
                    }
                }
                else
                {
                    result = await userManager.UpdateAsync(userExists);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("GetAll");
                    }
                    else
                    {

                    }
                }
            }
            return View(user);
        }


        public async Task<IActionResult> Form(Guid? IdUsuario)
        {
            if (IdUsuario == null)
            {
                return View(new IdentityUser());
            }
            else
            {
                var users = await userManager.FindByIdAsync(IdUsuario.ToString());
                return View(users);
            }
        }
    }
}

PL/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shopping Center</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Shopping Center</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (SignInManager.IsSignedIn(User))
                        {
                            @if(User.IsInRole("User")){
                               
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="GetAllProducto">Venta</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Venta" asp-action="Cart">Carrito</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Historial" asp-action="GetAll">Historial</a>
                                </li>
                            } 
                            @if(User.IsInRole("Admin")){
                                @* <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="GetAll">Rol</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="GetAll">Usuario</a>
                                </li> *@
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="GetAll">Producto</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Sucursal" asp-action="GetAll">Sucursal</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="SucursalProducto" asp-action="Index">Ver Sucursales</a>
                                </li>

                            }
                                @*<div class="col-md-4">
                            @Html.LabelFor(model => Model.Sucursal.Sucursales)
                            @Html.DropDownListFor(model => Model.Sucursal.IdSucursal, new SelectList(Model.Sucursal.Sucursales, "IdSucursal", "Nombre"), "Selecciona una Sucursal", new { @id = "ddlSucursal", @class = "form-control" })
                            </div>*@
                            @* </li> *@
                            @*<partial name="_LayoutDDL" />*@
                        }
                        else
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        }
                        

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PL/Views/Shared/_LayoutDDL.cshtml
@model ML.SucursalProducto
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<li class="nav-item">

    <div class="col-md-4">
    @Html.LabelFor(model => Model.Sucursal.Sucursales)
    @Html.DropDownListFor(model => Model.Sucursal.IdSucursal, new SelectList(Model.Sucursal.Sucursales, "IdSucursal", "Nombre"), "Selecciona una Sucursal", new { @id = "ddlSucursal", @class = "form-control" })
    </div>
</li>